---
- name: 'cleanup'
  hosts: localhost
  tasks:
  - name: 'destroy server'
    os_server:
      auth:
        auth_url: https://keystone.isis.vanderbilt.edu:5000/v2.0
        # START CHANGE
        username: 
        password: 
        # END CHANGE
        project_name: Cloud Class
      flavor: m1.small
      floating_ips:
        - 129.59.107.80
      image: ubuntu-14.04
      # START CHANGE
      key: /vagrant/default.pem
      key_name: default
      # END CHANGE
      name: rad_server_r
      network: b16b0244-e1b5-4d36-90ff-83a0d87d8682
      region_name: regionOne
      security_groups: default
      state: absent
...