---
- name: 'client setup'
  hosts: localhost
  pre_tasks:
  - name: 'client setup packages'
    raw: apt-get install -y build-essential libssl-dev libffi-dev 

  tasks:
  - name: 'launch server'
    os_server:
      auth:
        auth_url: https://keystone.isis.vanderbilt.edu:5000/v2.0
        # START CHANGE
        username: mccord1
        password: Webster3
        # END CHANGE
        project_name: Cloud Class
      flavor: m1.small
      floating_ips:
        - 129.59.107.50
      image: ubuntu-14.04
      # START CHANGE
      key: /vagrant/dannyas3key.pem
      key_name: dannyas3key
      # END CHANGE
      name: rad_server_r
      network: b16b0244-e1b5-4d36-90ff-83a0d87d8682
      region_name: regionOne
      security_groups: default
      state: present
      timeout: 200

  - name: 'wait for ssh server to start'
    pause: seconds=20


- name: 'horizon setup'
  hosts: horizon
  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks :
  - name: 'copy mr_thread.py'
    copy: src=/vagrant/mr_thread.py dest=/home/ubuntu/mr_thread.py owner=ubuntu

  - name: 'copy mr_framework.py'
    copy: src=/vagrant/mr_framework.py dest=/home/ubuntu/mr_framework.py owner=ubuntu

  - name: 'copy mapreduce.py'
    copy: src=/vagrant/mapreduce.py dest=/home/ubuntu/mapreduce.py owner=ubuntu

  - name: 'copy obj_retrieve.py'
    copy: src=/vagrant/obj_retrieve.py dest=/home/ubuntu/obj_retrieve.py owner=ubuntu

  - name: 'copy Dockerfile'
    copy: src=/vagrant/Dockerfile dest=/home/ubuntu/Dockerfile owner=ubuntu

  - name: 'server setup update'
    raw: apt-get update

  - name: 'server install recommended docker packages'
    raw: apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual

  - name: 'server install CA ca-certificates'
    raw: apt-get install apt-transport-https ca-certificates
    
  - name: 'server add GPG key'
    raw: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

  - name: 'server get docker from repo'
    raw: echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | tee /etc/apt/sources.list.d/docker.list

  - name: 'server update apt package index'
    raw: apt-get update

  - name: 'server cache docker policy'
    raw: apt-cache policy docker-engine

  - name: 'server install docker'
    raw: apt-get install docker-engine

#   - name: ''

# sudo -s
# cp /lib/systemd/system/docker.service /etc/systemd/system/docker.service
# vi   /etc/systemd/system/docker.service
# (or use whatever editor you are familiar with). Search for the line that starts with  ExecStart=
# At the end of this line, insert --mtu=1400 so that the modified line looks like this:
# ExecStart=/usr/bin/docker daemon -H fd:// –mtu=1400
# save and close the file, and do the following:
# systemctl daemon-reload
# I also did one more thing but I am not sure if it is needed or not. You can do this step also. No harm. 
# vi /etc/default/docker

# and look for the commented line that had DOCKER_OPTS in it. Uncomment the line and modify it to look like this.

# DOCKER_OPTS="--mtu 1400 --dns 8.8.8.8 --dns 8.8.4.4"

# Note, there are 2 dashes before mtu and dns. Now do the following

# prompt>  service docker restart


...