---
- name: 'client setup'
  hosts: localhost
  pre_tasks:
  - name: 'client setup packages'
    raw: apt-get install -y python python-dev python-pip build-essential libssl-dev libffi-dev 

  - name: 'client setup python packages'
    raw: pip install shade

  tasks:
  - name: 'launch server'
    os_server:
      auth:
        auth_url: https://keystone.isis.vanderbilt.edu:5000/v2.0
        # START CHANGE
        username: 
        password: 
        # END CHANGE
        project_name: Cloud Class
      flavor: m1.small
      floating_ips:
        - 129.59.107.50
      image: ubuntu-14.04
      # START CHANGE
      key: /vagrant/default.pem
      key_name: default
      # END CHANGE
      name: rad_server_r
      network: b16b0244-e1b5-4d36-90ff-83a0d87d8682
      region_name: regionOne
      security_groups: default
      state: present
      timeout: 200

  - name: 'wait for ssh server to start'
    pause: seconds=20


- name: 'horizon setup'
  hosts: horizon
  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks :
  - name: 'copy mr_thread.py'
    copy: src=/vagrant/mr_thread.py dest=/home/ubuntu/mr_thread.py owner=ubuntu

  - name: 'copy mr_framework.py'
    copy: src=/vagrant/mr_framework.py dest=/home/ubuntu/mr_framework.py owner=ubuntu

  - name: 'copy mapreduce.py'
    copy: src=/vagrant/mapreduce.py dest=/home/ubuntu/mapreduce.py owner=ubuntu

  - name: 'copy obj_retrieve.py'
    copy: src=/vagrant/obj_retrieve.py dest=/home/ubuntu/obj_retrieve.py owner=ubuntu

  - name: 'copy Dockerfile'
    copy: src=/vagrant/Dockerfile dest=/home/ubuntu/Dockerfile owner=ubuntu

  - name: 'copy .openrc.sh'
    copy: src=/vagrant/.openrc.sh dest=/home/ubuntu/.openrc.sh owner=ubuntu

  - name: 'copy energy-sorted100M.csv'
    copy: src=/vagrant/energy-sorted100M.csv dest=/home/ubuntu/energy-sorted100M.csv owner=ubuntu

  - name: 'server setup update'    
    raw: apt-get update

  - name: 'server setup packages'
    raw: apt-get install -y python python-dev python-pip

  - name: 'server setup python packages'
    raw: pip install python-swiftclient python-keystoneclient



  # all the stuff below needs to be run manually since grub has been locally modified
  - name: 'install docker'
    raw: curl -sSL https://get.docker.com/ | sh

# source openrc.sh
# python obj_retrieve.py
# Note that python obj_retrieve.py mostly fails due to an incomplete read

# sudo docker build .

# ssh into vm:
# ssh -i default.pem -o StrictHostKeyChecking=no ubuntu@129.59.107.50
# chmod 700 mapreduce.py
# sudo docker run -v /home/ubuntu:/assign3 -it -d --name test python:2.7.9
# sudo docker exec test python /assign3/mapreduce.py /assign3/energy-sorted100M.csv

...